---
apiVersion: v1
kind: Service
metadata:
  name: gotham
spec:
  ports:
    - port: 4000
      targetPort: 443
  selector:
    app: gotham
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gotham
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gotham
  template:
    metadata:
      labels:
        app: gotham
    spec:
      containers:
        - name: gotham
          image: roohoo/gotham:0.0.1
          ports:
            - name: ssl-port
              containerPort: 443
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: chore-website
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - chores.roohoo.dev
      secretName: chores-tls
  rules:
    - host: chores.roohoo.dev
      http:
        paths:
          - path: /
            backend:
              serviceName: gotham
              servicePort: 443
